<a href="https://colab.research.google.com/github/dennisddschulz/cas-artificial-intelligence/blob/main/01_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Manuell

In [2]:
import numpy as np

- Natürliche Zahlen
- Ganze Zahlen
- Rationale Zahlen
- Rationale Zahlen und Irrationale Zahlen - > R
- Complexe Zahlen (Quantum Comp und Frequenz-Analyse) -> C schliesst R ein

In [3]:
X = [1,2,3,4,5,6,7,8,9,10]
X = np.array(X).astype(np.float32)

In [4]:
X

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [5]:
X = np.arange(1,11).astype(np.float32)
X

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [6]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# List comprehension
Y = [2*x + 6 for x in X]
print(Y)

[np.float32(8.0), np.float32(10.0), np.float32(12.0), np.float32(14.0), np.float32(16.0), np.float32(18.0), np.float32(20.0), np.float32(22.0), np.float32(24.0), np.float32(26.0)]


Wir erstellen hier eine Liste.
[   ]

2*x + 6 für jedes Element x in X

In [8]:
len(X)

10

(m_deriv
b_deriv)
m_deriv ist die partielle Ableitung nach m (Gewicht)
b_deriv ist --- nach b (Bias)

$MSE = 1/N\sum_{i=0} ^N (Y_i - (mX_i + b))^2$





In [10]:
def update_weights(m, b, X, Y, learning_rate):
    m_deriv = 0
    b_deriv = 0
    N = len(X)
    # Ableitung MSE
    for i in range(N): # pytorch - backward # gradient tape
        # Calculate partial derivatives
        # -x (innere Ableitung) * 2(y - (mx + b)) (äussere Ableitung)
        m_deriv += -2*X[i] * (Y[i] - (m*X[i] + b))

        # -2(y - (mx + b))
        b_deriv += -2*(Y[i] - (m*X[i] + b))


    # We subtract because the derivatives point in direction of steepest ascent
    m -= (m_deriv / float(N)) * learning_rate # später - in pytorch step
    b -= (b_deriv / float(N)) * learning_rate
    history_m.append(m)
    history_b.append(b)

    return m,b


In [13]:
def train(epochs, learning_rate:int)-> tuple[float, float]:
    m=0
    b=0
    for epoch in range(epochs):
        # abbruchskriterium - "early stopping"
        m,b = update_weights(m, b, X, Y, learning_rate)
        if epoch%200==0:
          print(f"Epoch: {epoch}, m: {m}, b: {b}")
    return m,b

In [16]:
epochs = 300000
history_m = []
history_b = []

In [17]:
train(epochs, learning_rate=1e-4)

Epoch: 0, m: 0.02199999988079071, b: 0.003399999812245369
Epoch: 200, m: 2.2229602336883545, b: 0.367326945066452
Epoch: 400, m: 2.672018527984619, b: 0.47920992970466614
Epoch: 600, m: 2.7594804763793945, b: 0.5387565493583679
Epoch: 800, m: 2.772343635559082, b: 0.5871947407722473
Epoch: 1000, m: 2.7698495388031006, b: 0.6330375671386719
Epoch: 1200, m: 2.7642290592193604, b: 0.6780449748039246
Epoch: 1400, m: 2.7580037117004395, b: 0.7225828170776367
Epoch: 1600, m: 2.751709461212158, b: 0.766727864742279
Epoch: 1800, m: 2.7454257011413574, b: 0.8104990720748901
Epoch: 2000, m: 2.739192485809326, b: 0.8539039492607117
Epoch: 2200, m: 2.7330105304718018, b: 0.8969454765319824
Epoch: 2400, m: 2.7268800735473633, b: 0.9396270513534546
Epoch: 2600, m: 2.7208006381988525, b: 0.9819516539573669
Epoch: 2800, m: 2.7147717475891113, b: 1.023922085762024
Epoch: 3000, m: 2.7087931632995605, b: 1.0655416250228882
Epoch: 3200, m: 2.702864646911621, b: 1.1068129539489746
Epoch: 3400, m: 2.6969857

(np.float32(2.0008667), np.float32(5.9940414))

In [ ]:
history_m[500]

2.0976302065442782

In [ ]:
history_b[1999]

5.998762289578513

In [ ]:
import matplotlib.pyplot as plt
plt.rcdefaults()
from pylab import rcParams
%matplotlib inline

In [ ]:

plt.figure(figsize=(12,8))
plt.plot(history_m[0:epochs])
plt.plot(history_b[0:epochs])

plt.axhline(y=2, xmin=0, xmax=epochs, c='r', linewidth=4,linestyle='--')
plt.axhline(y=6, xmin=0, xmax=epochs, c='b', linewidth=4, linestyle=':')
plt.ylabel('m',fontsize= 18)
plt.xlabel('b',fontsize= 18)
plt.legend(['m', 'b'], loc='upper right', fontsize= 18);

In [ ]:
import torch
from torch import nn

In [ ]:
X, Y

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 [8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0, 22.0, 24.0, 26.0])

## Mit PyTorch

### Aufgabe 1:
1. Eigene function definieren mit ZWEI vars
2. Andere X und Y werte
3. LR varieren und das training beobachten (zu hohe, zu niedrige LR)
  - Macht ein LR range [from, to] - z.B. for loop
  - nimmt das beste LR (minimaler Loss, keine NaNs)
  - "Grid Search"
4. Plot die wahre und die predictete Funtionen gegeneinander

In [ ]:
# -*- coding: utf-8 -*-
import torch
import math

dtype = torch.float
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

# Create Tensors to hold input and outputs.
# By default, requires_grad=False, which indicates that we do not need to
# compute gradients with respect to these Tensors during the backward pass.
x = torch.linspace(1, 10, 10, dtype=dtype)
y = 2*x + 6

# Create random Tensors for weights.
# 2 weights: a and b
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), dtype=dtype, requires_grad=True)
b = torch.randn((), dtype=dtype, requires_grad=True)

learning_rate = 1e-3
for t in range(2000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a*x + b

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 0:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad


        # Manually zero the gradients after updating weights
        a.grad = None
        b.grad = None


print(f'Result: y = {a.item()} + {b.item()} x')

0 122.40975952148438
100 28.65900230407715
200 12.351658821105957
300 5.3234171867370605
400 2.2943193912506104
500 0.9888259172439575
600 0.42617329955101013
700 0.1836758255958557
800 0.0791618600487709
900 0.034117262810468674
1000 0.01470418181270361
1100 0.006337410304695368
1200 0.00273139332421124
1300 0.0011773051228374243
1400 0.0005074546788819134
1500 0.00021875405218452215
1600 9.42852784646675e-05
1700 4.061705112690106e-05
1800 1.7507863958599046e-05
1900 7.5416837717057206e-06
Result: y = 2.0001769065856934 + 5.998767852783203 x


## Mit PyTorch und für komplexe nicht-lineare Funktion


### Aufgabe 2
1. Define own non-linear function
2. 5 weights y = a + b x + c x^2 + d x^3 +c x^4
3. In case grade 4 is not enough, try grade 5
4. Plot the results in each case real function vs approximation

In [ ]:
# -*- coding: utf-8 -*-
import torch
import math

dtype = torch.float
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)

# Create Tensors to hold input and outputs.
# By default, requires_grad=False, which indicates that we do not need to
# compute gradients with respect to these Tensors during the backward pass.
x = torch.linspace(-math.pi, math.pi, 2000, dtype=dtype)
y = torch.sin(x)


# Create random Tensors for weights. For a third order polynomial, we need
# 4 weights: y = a + b x + c x^2 + d x^3
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
a = torch.randn((), dtype=dtype, requires_grad=True)
b = torch.randn((), dtype=dtype, requires_grad=True)
c = torch.randn((), dtype=dtype, requires_grad=True)
d = torch.randn((), dtype=dtype, requires_grad=True)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        print(t, loss.item())

    # Use autograd to compute the backward pass. This call will compute the
    # gradient of loss with respect to all Tensors with requires_grad=True.
    # After this call a.grad, b.grad. c.grad and d.grad will be Tensors holding
    # the gradient of the loss with respect to a, b, c, d respectively.
    loss.backward()

    # Manually update weights using gradient descent. Wrap in torch.no_grad()
    # because weights have requires_grad=True, but we don't need to track this
    # in autograd.
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad
        d -= learning_rate * d.grad

        # Manually zero the gradients after updating weights
        a.grad = None
        b.grad = None
        c.grad = None
        d.grad = None

print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

## Mit PyTorch und nn module

### Aufgabe 3 (wenn 1 und 2 fertig sind) - optional
1. Wie Augabe 2 nur mit nn lösen (d.h. zu approximierende Funktion, gleiche Werte, gleicher Polynom) - nur alles mit nn alalog dem Bespiel unten

2. Loss während dem Training plotten

In [ ]:
# -*- coding: utf-8 -*-
import torch
import math


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

In [ ]:
x.shape

torch.Size([2000])

In [ ]:
# p = torch.tensor([1, 2, 3])
x.unsqueeze(-1).shape

torch.Size([2000, 1])

In [ ]:
# For this example, the output y is a linear function of (x, x^2, x^3), so
# we can consider it as a linear layer neural network. Let's prepare the
# tensor (x, x^2, x^3).
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)
xx

tensor([[ -3.1416,   9.8696, -31.0063],
        [ -3.1384,   9.8499, -30.9133],
        [ -3.1353,   9.8301, -30.8205],
        ...,
        [  3.1353,   9.8301,  30.8205],
        [  3.1384,   9.8499,  30.9133],
        [  3.1416,   9.8696,  31.0063]])

In [ ]:
fc = torch.nn.Linear(3, 1)
fc(xx).shape

torch.Size([2000, 1])

In [ ]:
flat = torch.nn.Flatten(0,1)

In [ ]:
out = fc(xx)
out.shape

torch.Size([2000, 1])

In [ ]:
flat(out).shape

torch.Size([2000])

In [ ]:

# In the above code, x.unsqueeze(-1) has shape (2000, 1), and p has shape
# (3,), for this case, broadcasting semantics will apply to obtain a tensor
# of shape (2000, 3)

# Use the nn package to define our model as a sequence of layers. nn.Sequential
# is a Module which contains other Modules, and applies them in sequence to
# produce its output. The Linear Module computes output from input using a
# linear function, and holds internal Tensors for its weight and bias.
# The Flatten layer flatens the output of the linear layer to a 1D tensor,
# to match the shape of `y`.
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1),

)

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as our loss function.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-6
for t in range(2000):

    # Forward pass: compute predicted y by passing x to the model. Module objects
    # override the __call__ operator so you can call them like functions. When
    # doing so you pass a Tensor of input data to the Module and it produces
    # a Tensor of output data.
    y_pred = model(xx)

    # Compute and print loss. We pass Tensors containing the predicted and true
    # values of y, and the loss function returns a Tensor containing the
    # loss.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero the gradients before running the backward pass.
    model.zero_grad()

    # Backward pass: compute gradient of the loss with respect to all the learnable
    # parameters of the model. Internally, the parameters of each Module are stored
    # in Tensors with requires_grad=True, so this call will compute gradients for
    # all learnable parameters in the model.
    loss.backward()

    # Update the weights using gradient descent. Each parameter is a Tensor, so
    # we can access its gradients like we did before.
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

# You can access the first layer of `model` like accessing the first item of a list
linear_layer = model[0]

# For linear layer, its parameters are stored as `weight` and `bias`.
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')

99 836.1294555664062
199 560.0737915039062
299 376.3053283691406
399 253.92047119140625
499 172.37890625
599 118.02490234375
699 81.77565002441406
799 57.58780288696289
899 41.43978500366211
999 30.6528377532959
1099 23.44274139404297
1199 18.620513916015625
1299 15.393159866333008
1399 13.231743812561035
1499 11.78315544128418
1599 10.811569213867188
1699 10.159427642822266
1799 9.721343040466309
1899 9.426800727844238
1999 9.228596687316895
Result: y = 0.011916369199752808 + 0.8403390645980835 x + -0.002055770717561245 x^2 + -0.0909973755478859 x^3


## ...mit einem Optimizer

### Aufgabe 4 (wenn 1, 2 und fertig sind) - optional
1. Wie Augabe 3 nur mit nn **und Optimizer** lösen
2. Loss während dem Training plotten und mit dem Plot von Aufgabe 3 vergleichen
3. BONUS: Adam, RMSprop, SGD

In [ ]:
# -*- coding: utf-8 -*-
import torch
import math


# Create Tensors to hold input and outputs.
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)

# Prepare the input tensor (x, x^2, x^3).
p = torch.tensor([1, 2, 3])
xx = x.unsqueeze(-1).pow(p)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use RMSprop; the optim package contains many other
# optimization algorithms. The first argument to the RMSprop constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-3
optimizer = torch.optim.RMSprop(model.parameters(), lr=learning_rate)
for t in range(2000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(xx)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()


linear_layer = model[0]
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x + {linear_layer.weight[:, 1].item()} x^2 + {linear_layer.weight[:, 2].item()} x^3')